# Generated by Django 4.2.6 on 2024-04-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jogador1", models.CharField(max_length=255)),
                ("jogador2", models.CharField(max_length=255)),
                ("venc", models.CharField(max_length=255)),
                ("datahora", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
