# Generated by Django 4.2.6 on 2024-04-10 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tile0", models.CharField(default=None, max_length=1, null=True)),
                ("tile1", models.CharField(default=None, max_length=1, null=True)),
                ("tile2", models.CharField(default=None, max_length=1, null=True)),
                ("tile3", models.CharField(default=None, max_length=1, null=True)),
                ("tile4", models.CharField(default=None, max_length=1, null=True)),
                ("tile5", models.CharField(default=None, max_length=1, null=True)),
                ("tile6", models.CharField(default=None, max_length=1, null=True)),
                ("tile7", models.CharField(default=None, max_length=1, null=True)),
                ("tile8", models.CharField(default=None, max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="jogo",
            name="proximo",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="jogo",
            name="board",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="jogo.board",
            ),
            preserve_default=False,
        ),
    ]
