# Generated by Django 5.0.4 on 2024-04-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jogo", "0002_board_jogo_proximo_jogo_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogo",
            name="senha",
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
