# Generated by Django 4.2.6 on 2024-04-24 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jogo", "0003_jogo_senha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogo",
            name="jogador1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jogador1_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="jogador2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jogador2_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
